### ISSUE TITLE
Exits the app if something is wrong

### ISSUE THREAD

**Issue by adraut** [Livshitz/Liv.CommandlineArguments#1]
If an exception occurs while parsing it is caught and then the application is exited.  This makes it almost impossible to debug when using as library (referencing the DLL instead of the project).  Throw the exception instead of exiting the app.  Let the developer decide what to do.

**Comment by Livshitz** [comment]
You are right.
Fixed in: https://github.com/Livshitz/Liv.CommandlineArguments/commit/60de04013a6255231ce3dac557f9ae22c9a49022
And updated nuget package (v. 1.1.5515.14738).
